#!/bin/bash

export SDK_DIR=<SDK_DIR>
export BASE_DIR=<BASE_DIR>
export ENV_NAME=<ENV_NAME>
export ENV_DIR=<ENV_DIR>
export DB_STARTER_SQL=<DB_STARTER_SQL>
export DB_NAME=<DB_NAME>
export SOURCE_FOLDER=<SOURCE_FOLDER>
export CORE_PROJECT=<CORE_PROJECT>
export MODULE_PROJECT_FORMAT=<MODULE_PROJECT_FORMAT>
export DISTRIBUTION_NAME=<DISTRIBUTION_NAME>
export TOMCAT_HTTP_PORT=<TOMCAT_HTTP_PORT>
export TOMCAT_SHUTDOWN_PORT=<TOMCAT_SHUTDOWN_PORT>
export DEBUG_PORT=<DEBUG_PORT>
export BACKUP_SERVER=
export BACKUP_FOLDER=
export BACKUP_FILE=
